### ISSUE TITLE
Redundancy with liftf and liftM

### ISSUE THREAD

**Issue by FayeAlephNil** [SamuelSchlesinger/Academic#1]
https://github.com/SamuelSchlesinger/Academic/blob/master/delude/Delude.hs#L42-L48

You can get rid of these definitions and replace them with calls to `liftM` and `liftM2` as they are equivalent `(->) r` being a monad

**Comment by SamuelSchlesinger** [comment]
Thanks! I'm at work but I changed it on my main machine and I'll push it up later. I felt weird about those functions, especially their names, but I used them so much that I felt like I should export them. I'm glad they're already a pattern. Where are those guys generally used?

**Comment by FayeAlephNil** [comment]
I haven't done enough Haskell besides messing around to honestly tell you but I'd guess in similar situations to what you're doing where you just need to "lift" (hence the name) a function up to a monad. For example if you wanted to make a function `a -> b` into a function `[a] -> [b]`, you could do `fmap f`, but you could also do `liftM f`, I don't know a case where it would be definitely required though. In fact you could replace liftM calls with fmap calls. Though with higher order liftM's (like liftM2) that won't work as `fmap (fmap f) /= liftM2 f`

Also, `const` should probably be here https://github.com/SamuelSchlesinger/Academic/blob/master/delude/Delude.hs#L100 as you use it in some other places
